### ISSUE TITLE
Unable to open file 

### ISSUE THREAD

**Issue by zsxgb** [nmduc/deep-ternary#1]
Traceback (most recent call last):
  File "train.py", line 125, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 53, in main
    dl.prepare()
  File "/home/zsx/deep-ternary/utils/data_loader.py", line 22, in prepare
    self.load_data()
  File "/home/zsx/deep-ternary/utils/data_loader.py", line 38, in load_data
    self.x = self.load_h5py(self.db_fname, n_x)
  File "/home/zsx/deep-ternary/utils/data_loader.py", line 26, in load_h5py
    with h5py.File(fname, 'r') as f:
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/media/minhduc/Windows/mduc_work_data/BCS/imagenet_val_32x32_5m.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by zsxgb** [comment]
If you do not provide the data, the cost of our learning will be greatly increased

**Comment by nmduc** [comment]
Hi,
I have just uploaded a small sample h5py database for training. Note that this file serves as an example only. In order to get a good performing model, you need a much bigger database with millions of patches. 
You can now run the training and testing.
